# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "hugo-theme-spartan"
license = "MIT"
licenselink = "https://github.com/itsmattburgess/hugo-theme-spartan/blob/main/LICENSE"
description = ""
homepage = "https://mattburgess.dev/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Matt Burgess"
  homepage = "https://mattburgess.dev"