theme = "hugo-theme-spartan"
title = "Spartan Theme"
copyright = "Copyright © {year} Your Name. All Rights Reserved."
summaryLength = 5
enableEmoji = true

[params]
github_username = "username"
twitter_username = "username"
linkedin_username = "username"
intro = "A clean, minimal Hugo theme"
description = "Spartan is a lightweight, clean and minimal hugo theme, designed for small blogs and personal websites. If you like lots of bells and whistles, this might not be the best theme for you."
oglocale = "en_GB"
ogtype= "blog"
author = "Your Name"

[[menu.main]]
  name = "Page 1"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Page 2"
  url = "/"
  weight = 2

[[menu.main]]
  name = "Page 3"
  url = "/"
  weight = 3

[[menu.main]]
  name = "Page 4"
  url = "/"
  weight = 4
